---
title: "Plots from R in a Julia-based Quarto file"
format: 
  html:
    code-fold: true
engine: julia
julia:
  exeflags: ["--project", "-tauto"]
fig-format: png
---

```{julia}
#| label: startup
using RCall
```

```{r}
#| label: dataframe
tibble::glimpse(dat <- lme4::sleepstudy)
NULL
```

@fig-latticeplot is generated by `lattice::xyplot`

```{r}
#| code-fold: true
#| label: fig-latticeplot
#| fig-cap: Panel plot of reaction time (ms.) versus days of sleep deprivation by subject
print(lattice::xyplot(Reaction ~ Days | Subject, dat, aspect=2.3, type=c("g","p","r")))
NULL
```

whereas @fig-ggplot2 is generated by the `ggplot2` package.

```{r}
#| code-fold: true
#| label: fig-ggplot2
#| fig-cap: Reaction time versus days of sleep deprivation without markers for Subject.
library(ggplot2)
print(
    ggplot(dat) + 
        geom_point(
            aes(x = Days, y = Reaction, color=Subject)
        ) +
        geom_line(
            aes(x = Days, y = Reaction, color = Subject)
        )
    )
NULL
```